### PR TITLE
Enable safe-string compatibility

### LINKED ISSUE #35: camomile doesn't compile with OCaml 4.06
The upcoming OCaml release (4.06) has now safe-string enabled by default. However camomile isn't compatible with safe-string yet.

I don't have time to make a PR but I'd be happy to give any kind of help in fixing this.

### PR DESCRIPTION
**Pull request by jpdeplaix**
Fixes #35

### CODE REVIEW

**Comment by hcarty** [comment]
Looks correct from a visual read-through.

**Comment by yoriyuki** [comment]
Thank you for PR!  I added further fixes and merged to the master.

Thank you again for your help. @jpdeplaix @hcarty

**Comment by jpdeplaix** [comment]
Thanks a lot ! Are you planning to make a release soon ?

**Comment by yoriyuki** [comment]
No.  Nowadays, people are mostly using GitHub repo directly.  The release only have a symbolic meaning.

I guess we are heading to the grand version 1.0.0, but to there are many things to be done for that.

**Comment by hcarty** [comment]
A release would be useful for 4.06.0 compatibility since it has safe-string enabled by default. Otherwise anything using camomile won't be usable from opam + 4.06.0 without pinning camomile.

**Comment by yoriyuki** [comment]
opam can't use github directly?

**Comment by jpdeplaix** [comment]
Yes it is possible but no it is bad idea. Stable packages obviously must not use the git version.
I'll do a PR to opam-repository that applies these commits as a patch tomorrow.

**Comment by hcarty** [comment]
Thank you @jpdeplaix

@yoriyuki A release gives a stable (meaning the code won't unexpectedly change) instance of the code to point to. Then users can point to the latest revision in git if they want to.

**Comment by yoriyuki** [comment]
I mean, opam can't use a specific revision on github directly?  If not, the release would be useful but I don't have much time now.

**Comment by jpdeplaix** [comment]
What do you mean by specific revision ? If you mean using a git tag it is basically what a release is. Otherwise it is partially possible but as said above: it's **really** a bad idea.
You are basically saying that you want us to make a release from a random commit.
Don't get me wrong, if you don't have time and need to make further adjustments to the code I understand, it can wait until the 4.06 release at least.

But anyway, I think that adding a patch to opam-repository is not a so good idea either as it changes the type of the interface and it would be different from the one taken from the archive. Maybe a trade-off could be to make a new branch from the 0.8.5 tag, apply the necessary patches and release it as 0.8.6 ?

**Comment by yoriyuki** [comment]
Then, we'll release 0.8.6, by tagging rel-0.8.6 and changing all numbers and dependencies (now we need OCaml >= 4.03).

**Comment by yoriyuki** [comment]
PR #38 is merged and tagged rel-0.8.6
You can think of rel-0.8.6 as the official release of ver. 0.8.6

**Comment by gasche** [comment]
@jpdeplaix, @hcarty, @toots: is one of you willing to package the new release for opam?

**Comment by rgrinberg** [comment]
@gasche I can do it.

**Comment by jpdeplaix** [comment]
I can do it too.

**Comment by jpdeplaix** [comment]
https://github.com/ocaml/opam-repository/pull/10486

**Pull request merged**
