### PR TITLE
Cleanup of opens and indentation

### PR DESCRIPTION
**Pull request by rgrinberg**
I've removed a few instances of open and replaced them with qualified usages. This is quite a bit easier to read/grep for contributors.

Also I've ocp-indented the entire code base. Sometimes people object to this as it makes the git history a bit uglier, but I think in Camomile's case where it was imported into github anyway, it makes little difference.

### CODE REVIEW

**Comment by yoriyuki** [comment]
I agree with using less open.  For indentation I'm not sure.  It's true that most files did not change from the time when they are imported, but still it makes git diff uglier and hard.

Another issue is that even we can fix the indentation now, could we enforce this style later?  Maybe we incorporate a style check into CI?

**Comment by rgrinberg** [comment]
Ok it's up to you. Note that enforcing this indentation is fairly simple.
All I did was run the sources through ocp-indent. It's the only consistent,
editor agnostic formatter that I know of (tuareg's indentation is neither)

**Comment by yoriyuki** [comment]
> Note that enforcing this indentation is fairly simple.

@rgrinberg Can we enforce this using a hook after `git push`?  If this is possible, could you set up this?

**Comment by rgrinberg** [comment]
Ok, will give it a try. Would be nice to have the hook

**Comment by rgrinberg** [comment]
I've looked into doing it and it's kind of a pain if you're using github. We need to use github's webook API which requires us to host the code somewhere. But I don't really have anywhere handy to do that.

 I can setup a pre-commit hook that the users can manually install, but obviously this isn't the same thing.

**Comment by yoriyuki** [comment]
Thank you for looking into it.

> I can setup a pre-commit hook that the users can manually install, but obviously this isn't the same thing. 

This is potentially useful for other projects.

**Pull request merged**
