### PR TITLE
V1.0 rc 1

### PR DESCRIPTION
**Pull request by yoriyuki**
I don't know this way is the good way to prepare a release candidate, but  I fixed small glitches in the build process and update the documentation.  The previous PR #63 is subsumed into this one.

I also propose removing Wiki, because no one can update them.

### CODE REVIEW

**Comment by rgrinberg** [comment]
Looks good. We should really just consider getting rid of all those copy lines and just put all the files in 1 dir. The alias module already separates what is private and what is public.

**Comment by rgrinberg** [comment]
Btw, `bigarray` should be a dependency in Camomile itself as well.

**Comment by yoriyuki** [comment]
> Btw, `bigarray` should be a dependency in Camomile itself as well.

Done.  If you are okay, I will prepare the release.  not sure how to use topkg...

**Comment by rgrinberg** [comment]
If you'd like I can prepare a small guide on how to do this. It's quite
simple. You can do a manual release as well if you'd like, the issue with
those is that the checksums of tarballs created by git (for each tag)
aren't stable. It's not a huge issue as the maintainers end up updating
them whenever they're out of sync. But if use topkg you upload your own
archive to github which avoids this issue forever.

**Pull request merged**
