### PR TITLE
Fix opam file

### PR DESCRIPTION
**Pull request by rgrinberg**
* Add build-test (even if it doens't work well yet)
* Remove name from the opam file. Since it's already inferred from the opam
  filename
* Don't add version to opam file. This is no longer recommended and unnecessary
* Fix maintainer to be @yoriyuki

### CODE REVIEW

**Comment by yoriyuki** [comment]
Do we need "comprehensive"?  As you know I first use this word but people doesn't seem to like it(?).

Also, we may be better to prepare 0.8.7 release, which supports OCaml 4.02.3 as well.  How do you think?

**Comment by rgrinberg** [comment]
@yoriyuki I already made the release. Sorry if I didn't make that clear. I
agree that comprehensive isn't really necessary. I just copied the original
description.

**Comment by yoriyuki** [comment]
I see.  Fixing just the wrong version number in README is not worth a new release.  I will edit to 

- remove the version number in README
- add changelog
- remove "comprehensive"

**Comment by yoriyuki** [comment]
- Changed camomile.descr to remove "comprehensive"
- Remove the version number from README and ChangeLog in PR #46 
Please review them and if you do not find a problem please merge it.

**Pull request merged**
